In [4]:
import pandas as pd
import numpy as np

#define the path to the CSV file
csv_file_path = 'data.csv'

#read the CSV file into a pandas DataFrame
df = pd.read_csv('TechTrend_Orders_2026-07-02.csv')

df.head()

,Order ID,Date,Product ID,Product Name,Category,Quantity Sold,Retail Price (ZAR),Cost Price (ZAR),Revenue (ZAR),COGS (ZAR),Gross Profit (ZAR),Customer Segment,Province
0,TT-2024-0302,2024-01-01,10,Jabra Evolve2 55,Headphones,2,8499,5100,16998,10200,6798,Student,KwaZulu-Natal
1,TT-2024-0458,2024-01-01,22,Razer Basilisk V3 X HyperSpeed,Gaming Mice,1,1649,910,1649,910,739,Working Professional,Eastern Cape
2,TT-2024-0141,2024-01-02,47,Anker PowerCore 26800 PD,Phone Accessories,2,1599,860,3198,1720,1478,Student,Eastern Cape
3,TT-2024-0377,2024-01-03,40,Bose SoundLink Mini II SE,Speakers,1,3799,2190,3799,2190,1609,Student,Western Cape
4,TT-2024-0277,2024-01-04,27,Zowie EC2-C,Gaming Mice,2,1699,950,3398,1900,1498,Student,Western Cape

In [7]:
df.head(100)

,Order ID,Date,Product ID,Product Name,Category,Quantity Sold,Retail Price (ZAR),Cost Price (ZAR),Revenue (ZAR),COGS (ZAR),Gross Profit (ZAR),Customer Segment,Province
0,TT-2024-0302,2024-01-01,10,Jabra Evolve2 55,Headphones,2,8499,5100,16998,10200,6798,Student,KwaZulu-Natal
1,TT-2024-0458,2024-01-01,22,Razer Basilisk V3 X HyperSpeed,Gaming Mice,1,1649,910,1649,910,739,Working Professional,Eastern Cape
2,TT-2024-0141,2024-01-02,47,Anker PowerCore 26800 PD,Phone Accessories,2,1599,860,3198,1720,1478,Student,Eastern Cape
3,TT-2024-0377,2024-01-03,40,Bose SoundLink Mini II SE,Speakers,1,3799,2190,3799,2190,1609,Student,Western Cape
4,TT-2024-0277,2024-01-04,27,Zowie EC2-C,Gaming Mice,2,1699,950,3398,1900,1498,Student,Western Cape
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,TT-2024-0323,2024-03-17,49,OtterBox Defender Series iPhone 15,Phone Accessories,2,999,510,1998,1020,978,Student,KwaZulu-Natal
96,TT-2024-0163,2024-03-19,16,HyperX Alloy Origins 65,Keyboards,2,1799,970,3598,1940,1658,Working Professional,Western Cape
97,TT-2024-0182,2024-03-21,2,SoundCore Nova X Pro,Headphones,2,2499,1380,4998,2760,2238,Student,KwaZulu-Natal
98,TT-2024-0001,2024-03-22,18,Royal Kludge RK84,Keyboards,1,1499,790,1499,790,709,Student,KwaZulu-Natal
99,TT-2024-0341,2024-03-22,36,UE Wonderboom 3,Speakers,2,1499,810,2998,1620,1378,Student,Gauteng

In [9]:
df.head(500)

,Order ID,Date,Product ID,Product Name,Category,Quantity Sold,Retail Price (ZAR),Cost Price (ZAR),Revenue (ZAR),COGS (ZAR),Gross Profit (ZAR),Customer Segment,Province
0,TT-2024-0302,2024-01-01,10,Jabra Evolve2 55,Headphones,2,8499,5100,16998,10200,6798,Student,KwaZulu-Natal
1,TT-2024-0458,2024-01-01,22,Razer Basilisk V3 X HyperSpeed,Gaming Mice,1,1649,910,1649,910,739,Working Professional,Eastern Cape
2,TT-2024-0141,2024-01-02,47,Anker PowerCore 26800 PD,Phone Accessories,2,1599,860,3198,1720,1478,Student,Eastern Cape
3,TT-2024-0377,2024-01-03,40,Bose SoundLink Mini II SE,Speakers,1,3799,2190,3799,2190,1609,Student,Western Cape
4,TT-2024-0277,2024-01-04,27,Zowie EC2-C,Gaming Mice,2,1699,950,3398,1900,1498,Student,Western Cape
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,TT-2024-0074,2024-12-29,50,Peak Design Mobile Case + Wallet,Phone Accessories,2,1299,680,2598,1360,1238,Student,Eastern Cape
496,TT-2024-0088,2024-12-29,15,Ducky One 3 TKL,Keyboards,2,3299,1880,6598,3760,2838,Working Professional,Gauteng
497,TT-2024-0312,2024-12-29,16,HyperX Alloy Origins 65,Keyboards,2,1799,970,3598,1940,1658,Student,Gauteng
498,TT-2024-0438,2024-12-29,26,Endgame Gear XM1r,Gaming Mice,3,1299,700,3897,2100,1797,Student,Western Cape
499,TT-2024-0233,2024-12-30,1,Sony WH-1000XM5,Headphones,3,5499,3190,16497,9570,6927,Working Professional,Gauteng

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            500 non-null    object
 1   Date                500 non-null    object
 2   Product ID          500 non-null    int64
 3   Product Name        500 non-null    object
 4   Category            500 non-null    object
 5   Quantity Sold       500 non-null    int64
 6   Retail Price (ZAR)  500 non-null    int64
 7   Cost Price (ZAR)    500 non-null    int64
 8   Revenue (ZAR)       500 non-null    int64
 9   COGS (ZAR)          500 non-null    int64
 10  Gross Profit (ZAR)  500 non-null    int64
 11  Customer Segment    500 non-null    object
 12  Province            500 non-null    object
dtypes: int64(7), object(6)
memory usage: 50.9+ KB

In [11]:
df.describe()

,Product ID,Quantity Sold,Retail Price (ZAR),Cost Price (ZAR),Revenue (ZAR),COGS (ZAR),Gross Profit (ZAR)
count,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000
mean,28.738000,1.652000,2119.900000,1182.980000,3522.74800,1966.100000,1556.648000
std,14.227938,0.635377,1383.302295,833.923844,2961.79434,1754.609329,1210.172207
min,1.000000,1.000000,499.000000,240.000000,499.00000,240.000000,259.000000
25%,17.000000,1.000000,1299.000000,680.000000,1773.25000,947.500000,806.250000
50%,28.000000,2.000000,1799.000000,970.000000,2799.00000,1530.000000,1249.000000
75%,42.000000,2.000000,2499.000000,1380.000000,4199.00000,2400.000000,1842.750000
max,50.000000,3.000000,8499.000000,5100.000000,25497.00000,15300.000000,10197.000000

In [12]:
df.isnull().sum()

Order ID              0
Date                  0
Product ID            0
Product Name          0
Category              0
Quantity Sold         0
Retail Price (ZAR)    0
Cost Price (ZAR)      0
Revenue (ZAR)         0
COGS (ZAR)            0
Gross Profit (ZAR)    0
Customer Segment      0
Province              0
dtype: int64

In [16]:
print(df.columns.tolist())

['Order ID', 'Date', 'Product ID', 'Product Name', 'Category', 'Quantity Sold', 'Retail Price (ZAR)', 'Cost Price (ZAR)', 'Revenue (ZAR)', 'COGS (ZAR)', 'Gross Profit (ZAR)', 'Customer Segment', 'Province']

In [19]:
df.groupby('Province')[['Revenue (ZAR)', 'Gross Profit (ZAR)']].sum()

               Revenue (ZAR)  Gross Profit (ZAR)
Province
Eastern Cape          168778               73788
Free State             59763               27193
Gauteng               666010              291740
KwaZulu-Natal         250916              112446
Limpopo                48171               21921
Mpumalanga             92458               40888
North West             84468               36398
Northern Cape          76368               33408
Western Cape          314442              140542